export const employees = [
  { name: "John Smith", department: "Engineering", position: "Software Engineer", dateOfHire: new Date("2020-02-15") },
  { name: "Sarah Johnson", department: "Marketing", position: "Marketing Manager", dateOfHire: new Date("2019-06-01") },
  { name: "James Williams", department: "Sales", position: "Sales Associate", dateOfHire: new Date("2021-01-10") },
  { name: "Patricia Brown", department: "Human Resources", position: "HR Specialist", dateOfHire: new Date("2018-03-25") },
  { name: "Michael Jones", department: "Engineering", position: "DevOps Engineer", dateOfHire: new Date("2017-07-30") },
  { name: "Linda Davis", department: "Finance", position: "Financial Analyst", dateOfHire: new Date("2020-11-05") },
  { name: "Robert Garcia", department: "Marketing", position: "Content Strategist", dateOfHire: new Date("2019-09-12") },
  { name: "Mary Martinez", department: "Sales", position: "Account Executive", dateOfHire: new Date("2021-04-18") },
  { name: "David Rodriguez", department: "Engineering", position: "Product Manager", dateOfHire: new Date("2016-12-22") },
  { name: "Jennifer Wilson", department: "Customer Support", position: "Support Specialist", dateOfHire: new Date("2018-08-14") },
  { name: "Charles Miller", department: "Finance", position: "Accountant", dateOfHire: new Date("2017-05-01") },
  { name: "Elizabeth Anderson", department: "Engineering", position: "Backend Developer", dateOfHire: new Date("2019-07-23") },
  { name: "Matthew Thomas", department: "Marketing", position: "SEO Specialist", dateOfHire: new Date("2020-03-19") },
  { name: "Barbara Lee", department: "Sales", position: "Sales Manager", dateOfHire: new Date("2016-09-08") },
  { name: "Joseph White", department: "Human Resources", position: "Recruiter", dateOfHire: new Date("2018-11-13") },
  { name: "Susan Harris", department: "Engineering", position: "Frontend Developer", dateOfHire: new Date("2019-12-27") },
  { name: "Steven Martin", department: "Finance", position: "Financial Advisor", dateOfHire: new Date("2021-05-02") },
  { name: "Jessica Thompson", department: "Marketing", position: "Graphic Designer", dateOfHire: new Date("2020-10-21") },
  { name: "Daniel Jackson", department: "Sales", position: "Sales Representative", dateOfHire: new Date("2017-02-14") },
  { name: "Karen Martinez", department: "Human Resources", position: "HR Manager", dateOfHire: new Date("2016-04-30") },
  { name: "Christopher Lopez", department: "Engineering", position: "Systems Analyst", dateOfHire: new Date("2019-11-17") },
  { name: "Nancy Gonzalez", department: "Finance", position: "Budget Analyst", dateOfHire: new Date("2018-06-25") },
  { name: "Paul Wilson", department: "Marketing", position: "Public Relations Specialist", dateOfHire: new Date("2019-10-05") },
  { name: "Sandra Carter", department: "Sales", position: "Customer Success Manager", dateOfHire: new Date("2020-01-16") },
  { name: "Mark Mitchell", department: "Engineering", position: "Network Engineer", dateOfHire: new Date("2017-08-29") },
  { name: "Ashley Perez", department: "Finance", position: "Investment Analyst", dateOfHire: new Date("2018-12-11") },
  { name: "Kevin Roberts", department: "Marketing", position: "Brand Manager", dateOfHire: new Date("2020-04-23") },
  { name: "Emily Turner", department: "Sales", position: "Sales Coordinator", dateOfHire: new Date("2021-06-09") },
  { name: "Brian Phillips", department: "Human Resources", position: "HR Assistant", dateOfHire: new Date("2019-05-14") },
  { name: "Laura Campbell", department: "Engineering", position: "Data Scientist", dateOfHire: new Date("2017-11-03") },
  { name: "Richard Parker", department: "Finance", position: "Treasurer", dateOfHire: new Date("2016-01-22") },
  { name: "Kimberly Evans", department: "Marketing", position: "Digital Marketing Specialist", dateOfHire: new Date("2018-04-10") },
  { name: "Anthony Edwards", department: "Sales", position: "Business Development Manager", dateOfHire: new Date("2020-08-14") },
  { name: "Deborah Collins", department: "Human Resources", position: "HR Coordinator", dateOfHire: new Date("2019-12-30") },
  { name: "Jason Stewart", department: "Engineering", position: "IT Support Specialist", dateOfHire: new Date("2017-03-18") },
  { name: "Michelle Morris", department: "Finance", position: "Controller", dateOfHire: new Date("2021-07-21") },
  { name: "David Rivera", department: "Marketing", position: "Social Media Manager", dateOfHire: new Date("2018-05-26") },
  { name: "Helen Bailey", department: "Sales", position: "Key Account Manager", dateOfHire: new Date("2020-09-07") },
  { name: "George Cooper", department: "Human Resources", position: "Compensation Analyst", dateOfHire: new Date("2019-02-17") },
  { name: "Catherine Ward", department: "Engineering", position: "Database Administrator", dateOfHire: new Date("2016-07-24") },
  { name: "Edward Morgan", department: "Finance", position: "Credit Analyst", dateOfHire: new Date("2021-02-10") },
  { name: "Megan Bell", department: "Marketing", position: "Event Coordinator", dateOfHire: new Date("2018-10-28") },
  { name: "Ryan Sanchez", department: "Sales", position: "Regional Sales Manager", dateOfHire: new Date("2017-06-22") },
  { name: "Betty Torres", department: "Human Resources", position: "Talent Acquisition Specialist", dateOfHire: new Date("2019-09-11") },
  { name: "Frank Rivera", department: "Engineering", position: "Security Analyst", dateOfHire: new Date("2016-03-15") },
  { name: "Donna Peterson", department: "Finance", position: "Tax Advisor", dateOfHire: new Date("2020-12-20") },
  { name: "Jack Gray", department: "Marketing", position: "Copywriter", dateOfHire: new Date("2018-02-05") },
  { name: "Margaret Ramirez", department: "Sales", position: "Territory Manager", dateOfHire: new Date("2021-01-12") },
];
