export const positions = [
  { name: 'Software Engineer' },
  { name: 'Marketing Manager' },
  { name: 'Sales Associate' },
  { name: 'HR Specialist' },
  { name: 'DevOps Engineer' },
  { name: 'Financial Analyst' },
  { name: 'Content Strategist' },
  { name: 'Account Executive' },
  { name: 'Product Manager' },
  { name: 'Support Specialist' },
  { name: 'Accountant' },
  { name: 'Backend Developer' },
  { name: 'SEO Specialist' },
  { name: 'Sales Manager' },
  { name: 'Recruiter' },
  { name: 'Frontend Developer' },
  { name: 'Financial Advisor' },
  { name: 'Graphic Designer' },
  { name: 'Sales Representative' },
  { name: 'HR Manager' },
  { name: 'Systems Analyst' },
  { name: 'Budget Analyst' },
  { name: 'Public Relations Specialist' },
  { name: 'Customer Success Manager' },
  { name: 'Network Engineer' },
  { name: 'Investment Analyst' },
  { name: 'Brand Manager' },
  { name: 'Sales Coordinator' },
  { name: 'HR Assistant' },
  { name: 'Data Scientist' },
  { name: 'Treasurer' },
  { name: 'Digital Marketing Specialist' },
  { name: 'Business Development Manager' },
  { name: 'HR Coordinator' },
  { name: 'IT Support Specialist' },
  { name: 'Controller' },
  { name: 'Social Media Manager' },
  { name: 'Key Account Manager' },
  { name: 'Compensation Analyst' },
  { name: 'Database Administrator' },
  { name: 'Credit Analyst' },
  { name: 'Event Coordinator' },
  { name: 'Regional Sales Manager' },
  { name: 'Talent Acquisition Specialist' },
  { name: 'Security Analyst' },
  { name: 'Tax Advisor' },
  { name: 'Copywriter' },
  { name: 'Territory Manager' },
];
