# Stage 1: Runner
FROM node:18-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat openssl

# Copy the pre-built application
COPY dist/datatable-api .

# Copy production dependencies and install them
COPY package.json pnpm-lock.yaml* ./
# Copy Prisma schema and generated client
COPY datatable-api/prisma ./datatable-api/prisma

RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile --prod
# RUN pnpm install --frozen-lockfile
RUN pnpm install prisma

RUN npm run prisma:generate

# Copy and setup entrypoint
COPY datatable-api/entrypoint.sh .
RUN chmod +x ./entrypoint.sh

EXPOSE 3000
ENTRYPOINT ["./entrypoint.sh"]
CMD ["node", "main.js"]
