# Stage 1: Runner
FROM node:18-alpine
WORKDIR /app

# Copy the pre-built application
COPY dist/datatable-api .

# Copy production dependencies and install them
COPY package.json pnpm-lock.yaml* ./
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile --prod

# Copy Prisma schema and generated client
COPY datatable-api/prisma ./datatable-api/prisma

# Copy and setup entrypoint
COPY datatable-api/entrypoint.sh .
RUN chmod +x ./entrypoint.sh

EXPOSE 3000
ENTRYPOINT ["./entrypoint.sh"]
CMD ["node", "main.js"]
