version: '3.5'
services:
  postgres:
    container_name: postgres_datatable
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: datatable
      PGDATA: /data/datatable
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
volumes:
  postgres:
    driver: local
