name: CI - Build and Deploy datatable projects

on:
  push:
    branches:
      - test_dockerhub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for nx affected
          filter: tree:0 # Optional, but recommended: reduce the size of the checkout with tree filtering, see https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@v4

      - name: Check for affected project
        id: check_affected
        run: |
          AFFECTED_APPS=$(npx nx show projects --affected)
          echo "Affected apps: $AFFECTED_APPS"
          if [[ "$AFFECTED_APPS" == *"datatable-api"* ]]; then
            echo "datatable-api is affected."
            echo "datatable_api_affected=true" >> $GITHUB_OUTPUT
          else
            echo "datatable-api is not affected."
            echo "datatable_api_affected=false" >> $GITHUB_OUTPUT
          fi

          if [[ "$AFFECTED_APPS" == *"datatable"* ]]; then
            echo "datatable is affected."
            echo "datatable_affected=true" >> $GITHUB_OUTPUT
          else
            echo "datatable is not affected."
            echo "datatable_affected=false" >> $GITHUB_OUTPUT
          fi

      - name: Build datatable-api
        if: steps.check_affected.outputs.datatable_api_affected == 'true'
        run: |
          npm run build:datatable-api

      - name: Build datatable
        if: steps.check_affected.outputs.datatable_affected == 'true'
        run: |
          npm run build:datatable

      - name: Login to Docker Hub
        if: steps.check_affected.outputs.datatable_api_affected == 'true' || steps.check_affected.outputs.datatable_affected == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: steps.check_affected.outputs.datatable_api_affected == 'true' || steps.check_affected.outputs.datatable_affected == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Build and push datatable-api
        if: steps.check_affected.outputs.datatable_api_affected == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./datatable-api/Dockerfile.ci
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/datatable-api:latest

      - name: Build and push datatable
        if: steps.check_affected.outputs.datatable_affected == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./datatable/Dockerfile.ci
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/datatable:latest
